import { KnowledgeItem } from './connector.interface';

// AUTO-GERADO de hipertms_v12/docs/manuais tecnicos/Manuais Tecnicos.
// NAO editar a mao — regenerar quando os manuais mudarem (script no chat).
// 97 chunks de 10 manuais.

export const MANUAIS_KB: KnowledgeItem[] = [
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos",
    content: "> Este guia vai orientá-lo desde o acesso ao sistema até o painel inicial, para que você comece a operar com facilidade.",
    tags: ["primeiros-passos", "primeiros", "passos"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › Acesso ao sistema › Faça seu login",
    content: "Acesse o endereço do HiperTMS no navegador e informe seu e-mail e senha cadastrados. Clique em **Entrar**.\n\nSe você esqueceu sua senha, utilize o link **\"Esqueci minha senha\"** na tela de login. Você receberá um e-mail com as instruções para criar uma nova senha.",
    tags: ["primeiros-passos", "primeiros", "passos", "acesso", "sistema", "faça", "login"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › Acesso ao sistema › Verifique seu e-mail ao criar uma conta nova",
    content: "Ao se cadastrar pela primeira vez, o sistema enviará um e-mail de confirmação. Clique no link recebido para ativar sua conta antes de fazer o primeiro acesso.",
    tags: ["primeiros-passos", "primeiros", "passos", "acesso", "sistema", "verifique", "mail", "criar"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › Configuração inicial (Onboarding) › Configure sua empresa antes de começar a operar",
    content: "Na primeira vez que você acessa o sistema, o HiperTMS apresenta um assistente de configuração. Ele guia você pelas informações essenciais da sua empresa — dados cadastrais, configurações fiscais e preferências iniciais.\n\nSiga as etapas do assistente na ordem apresentada. Cada passo salva automaticamente ao avançar. Quando o progresso atingir 100%, você será direcionado ao painel principal.\n\n> Você pode retomar o assistente a qualquer momento acessando **Administração → Perfil da Empresa**, caso precise ajustar alguma informação.",
    tags: ["primeiros-passos", "primeiros", "passos", "configuração", "inicial", "onboarding", "configure", "empresa"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › O painel inicial (Cockpit) › Acompanhe o que importa hoje",
    content: "Ao entrar no sistema, você verá o **Cockpit do Dia** — uma visão geral do que está acontecendo agora na sua operação. Ele apresenta acesso rápido a todas as áreas do sistema organizadas por hubs de negócio.\n\nOs hubs disponíveis são:\n\n- **Vendas** — cotações e embarques em andamento\n- **Operação** — cargas, viagens e documentos fiscais\n- **Cadastros** — clientes, parceiros e fornecedores\n- **Frota** — veículos, motoristas e manutenção\n- **Compras** — solicitações, pedidos e estoque\n- **Financeiro** — contas, faturas e orçamento\n- **Equipes** — atividades, tarefas e notificações\n- **Precificação** — tabelas de frete e configurações\n\nClique em qualquer hub para ver as funcionalidades disponíveis naquela área.",
    tags: ["primeiros-passos", "primeiros", "passos", "painel", "inicial", "cockpit", "acompanhe", "importa"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › O painel inicial (Cockpit) › Veja o resumo operacional",
    content: "Acesse **Dashboard → Operacional** (ou navegue pelo menu lateral) para visualizar o painel com os totais por status de cotações, embarques, cargas e viagens.\n\nO painel também exibe gráficos de série temporal da operação logística e um resumo da situação da frota (veículos e motoristas por status).",
    tags: ["primeiros-passos", "primeiros", "passos", "painel", "inicial", "cockpit", "veja", "resumo"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › Navegação › Use o menu lateral para se movimentar",
    content: "O menu lateral esquerdo organiza todas as áreas do sistema. Clique no ícone ou nome do hub desejado para acessar suas funcionalidades.\n\nNo topo da tela você encontra notificações, acesso ao seu perfil e, quando disponível, o widget de chat para suporte.",
    tags: ["primeiros-passos", "primeiros", "passos", "navegação", "menu", "lateral", "para", "movimentar"],
  },
  {
    topic: "hipertms-01-primeiros-passos",
    category: "primeiros-passos",
    title: "Primeiros Passos › Minha conta › Atualize seus dados pessoais",
    content: "Acesse **Administração → Minha Conta** para editar seu nome, e-mail, senha e foto de perfil. Mantenha sempre seus dados atualizados.",
    tags: ["primeiros-passos", "primeiros", "passos", "minha", "conta", "atualize", "seus", "dados"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas",
    content: "> A área de Vendas concentra todo o ciclo comercial: desde a proposta de frete até a conversão em embarque. Aqui você gera cotações, acompanha pedidos dos clientes e gerencia oportunidades.",
    tags: ["vendas"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Cotações › Crie uma nova cotação de frete",
    content: "Acesse **Vendas → Cotações** e clique em **Nova Cotação**.\n\nPreencha os dados da operação:\n\n- **Remetente e destinatário** — origem e destino da carga\n- **Tomador** — quem contratará e pagará pelo frete\n- **Tipo de operação** — FCL (carga fechada) ou LCL (carga fracionada)\n- **Veículo** — tipo de veículo necessário\n- **Mercadoria** — descrição, peso, volumes e valor declarado\n\nO sistema calculará automaticamente o frete com base nas suas tabelas de precificação cadastradas. Você pode revisar e ajustar valores antes de salvar.\n\nAo finalizar, a cotação fica com status **Rascunho** e você pode enviá-la ao cliente ou convertê-la diretamente em embarque.",
    tags: ["vendas", "cotações", "crie", "nova", "cotação", "frete"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Cotações › Consulte e gerencie suas cotações",
    content: "Na lista de cotações, você visualiza todas as propostas com seus respectivos status:\n\n- **Rascunho** — em elaboração\n- **Enviada** — proposta enviada ao cliente\n- **Aprovada** — cliente aceitou\n- **Recusada** — proposta não aceita\n- **Convertida** — gerou embarque\n\nUse os filtros de data, cliente e status para localizar cotações rapidamente. Clique em qualquer linha para ver os detalhes ou editar.",
    tags: ["vendas", "cotações", "consulte", "gerencie", "suas"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Cotações › Converta uma cotação em embarque",
    content: "Com uma cotação aprovada aberta, clique em **Converter em Embarque**. O sistema cria automaticamente o embarque com todos os dados já preenchidos, sem precisar digitar novamente.",
    tags: ["vendas", "cotações", "converta", "cotação", "embarque"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Embarques › Crie um novo embarque",
    content: "Acesse **Vendas → Embarques** e clique em **Novo Embarque**.\n\nUm embarque representa o pedido de transporte do seu cliente. Preencha:\n\n- **Tomador** — cliente que contrata o serviço\n- **Remetente e destinatário** — pontos de coleta e entrega\n- **Dados da carga** — tipo, peso, volumes e valor das mercadorias\n- **NF-e** — você pode vincular as notas fiscais manualmente ou importar via XML\n\nO sistema calcula o frete com base na precificação vigente. Após salvar, o embarque entra no fluxo operacional e pode ser incluído em uma viagem.",
    tags: ["vendas", "embarques", "crie", "novo", "embarque"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Embarques › Acompanhe o status dos embarques",
    content: "Na lista de embarques você encontra cada pedido com seu status atual:\n\n- **Aguardando** — criado, aguarda programação\n- **Em andamento** — incluído em uma viagem em execução\n- **Entregue** — carga entregue ao destinatário\n- **Cancelado** — embarque cancelado\n\nClique em um embarque para ver detalhes, eventos de rastreamento, documentos anexados e informações financeiras.",
    tags: ["vendas", "embarques", "acompanhe", "status"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Embarques › Vincule notas fiscais a um embarque",
    content: "Dentro do detalhe do embarque, acesse a aba **NF-e / XML** para vincular as notas fiscais eletrônicas do cliente. Você pode fazer o upload do arquivo XML ou importar notas já cadastradas no sistema.",
    tags: ["vendas", "embarques", "vincule", "notas", "fiscais", "embarque"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Embarques › Gere o e-mail de confirmação de coleta (Booking)",
    content: "Com um embarque selecionado, utilize a função **Gerar E-mail de Booking** para criar automaticamente a mensagem de confirmação de coleta com os dados da operação. Copie o texto gerado e envie ao remetente.\n\n> Para personalizar o modelo do e-mail, acesse **Vendas → Modelo de E-mail de Booking**.",
    tags: ["vendas", "embarques", "gere", "mail", "confirmação", "coleta", "booking"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › NF-e XML (Importação de notas fiscais) › Importe as notas fiscais do seu cliente",
    content: "Acesse **Vendas → NFe XML** para gerenciar as notas fiscais eletrônicas recebidas de clientes. Você pode fazer o upload de arquivos XML individualmente ou em lote.\n\nApós a importação, o sistema extrai automaticamente os dados da nota (remetente, destinatário, valor, peso estimado) e permite vinculá-la a embarques existentes ou criar um novo embarque a partir dela.",
    tags: ["vendas", "importação", "notas", "fiscais", "importe", "cliente"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › NF-e XML (Importação de notas fiscais) › Crie um embarque diretamente de um XML",
    content: "Na lista de NFe XML, selecione uma nota importada e clique em **Criar Embarque**. Os dados do remetente, destinatário e carga serão preenchidos automaticamente com as informações da nota fiscal.",
    tags: ["vendas", "importação", "notas", "fiscais", "crie", "embarque", "diretamente"],
  },
  {
    topic: "hipertms-02-vendas",
    category: "vendas",
    title: "Vendas › Oportunidades (Funil SDR) › Gerencie o funil de prospecção comercial",
    content: "Acesse **Vendas → Oportunidades** para visualizar e movimentar as oportunidades de novos clientes no funil de vendas.\n\nCada oportunidade representa uma empresa em potencial, com seus dados de contato e estágio no processo comercial:\n\n- **Prospecção** — empresa identificada, ainda sem contato\n- **Qualificação** — primeiro contato realizado\n- **Proposta** — cotação enviada\n- **Negociação** — proposta em análise\n- **Ganho / Perdido** — resultado da negociação\n\nClique em uma oportunidade para registrar atividades, agendar follow-ups e visualizar o histórico de interações.",
    tags: ["vendas", "oportunidades", "funil", "gerencie", "prospecção", "comercial"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação",
    content: "> A área de Operação é onde a logística acontece. Aqui você programa cargas, planeja e executa viagens, controla paradas e emite os documentos fiscais de transporte.",
    tags: ["operacao", "operação"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › Cargas › Visualize e programe a carga do dia",
    content: "Acesse **Operação → Cargas** para ver todos os embarques disponíveis para programação, organizados por status e data.\n\nA tela de Programação de Cargas apresenta os embarques aguardando coleta e permite agrupá-los em viagens, de acordo com a rota, veículo e capacidade disponível.\n\nUse os filtros de data, origem e destino para encontrar as cargas do período desejado.",
    tags: ["operacao", "operação", "cargas", "visualize", "programe", "carga"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › Viagens › Crie uma nova viagem",
    content: "Acesse **Operação → Viagens** e clique em **Nova Viagem**.\n\nUma viagem reúne um conjunto de embarques que serão transportados juntos por um veículo e motorista. Preencha:\n\n- **Veículo** — veículo que realizará o transporte\n- **Motorista** — responsável pela viagem\n- **Embarques** — selecione os embarques que compõem esta viagem\n- **Rota** — defina a sequência de coletas e entregas\n- **Diária do motorista** — valor de adiantamento, se aplicável\n\nO sistema calcula automaticamente o peso total, cubagem e a margem financeira da viagem.",
    tags: ["operacao", "operação", "viagens", "crie", "nova", "viagem"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › Viagens › Acompanhe o andamento de uma viagem",
    content: "Na lista de viagens, clique em qualquer viagem para ver seus detalhes:\n\n- **Paradas** — sequência de coletas e entregas programadas\n- **Embarques** — pedidos incluídos na viagem\n- **Eventos** — rastreamento e ocorrências registradas\n- **Documentos** — CT-e, MDF-e e comprovantes vinculados\n- **Financeiro** — custos, receitas e margem da viagem\n\nOs status possíveis de uma viagem são: **Planejada**, **Em andamento**, **Concluída** e **Cancelada**.",
    tags: ["operacao", "operação", "viagens", "acompanhe", "andamento", "viagem"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › Viagens › Gerencie as paradas de uma viagem",
    content: "Acesse **Operação → Gestão de Paradas** para visualizar e reorganizar a sequência de coletas e entregas de todas as viagens ativas.\n\nVocê pode arrastar e reordenar as paradas, registrar confirmações de coleta/entrega e adicionar observações operacionais a cada ponto da rota.",
    tags: ["operacao", "operação", "viagens", "gerencie", "paradas", "viagem"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › Viagens › Registre eventos e ocorrências",
    content: "Dentro do detalhe de um embarque ou viagem, acesse a aba **Eventos** para registrar ocorrências durante o transporte — como tentativas de entrega, avarias, atrasos ou qualquer outra intercorrência.\n\nCada evento registrado compõe o histórico de rastreamento do embarque, visível para a equipe interna.",
    tags: ["operacao", "operação", "viagens", "registre", "eventos", "ocorrências"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › CT-e (Conhecimento de Transporte Eletrônico) › Consulte os CT-e emitidos",
    content: "Acesse **Operação → CT-e** para visualizar todos os Conhecimentos de Transporte Eletrônicos da sua operação.\n\nA lista apresenta os CT-e com número, tomador, valor, data de emissão e situação fiscal. Clique em qualquer CT-e para ver o DANFE resumido, os dados completos e os documentos vinculados.",
    tags: ["operacao", "operação", "conhecimento", "transporte", "eletrônico", "consulte", "emitidos"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › CT-e (Conhecimento de Transporte Eletrônico) › Entenda os status de um CT-e",
    content: "- **Autorizado** — emitido e validado pela SEFAZ\n- **Cancelado** — cancelamento autorizado pela SEFAZ\n- **Denegado** — emissão negada\n- **Em processamento** — aguardando retorno da SEFAZ\n\n> A emissão de CT-e é realizada a partir dos embarques. Consulte a equipe responsável pela configuração fiscal para habilitar a emissão integrada.",
    tags: ["operacao", "operação", "conhecimento", "transporte", "eletrônico", "entenda", "status"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › MDF-e (Manifesto de Documentos Fiscais) › Consulte os MDF-e emitidos",
    content: "Acesse **Operação → MDF-e** para visualizar todos os Manifestos de Documentos Fiscais Eletrônicos.\n\nO MDF-e é o documento que acompanha a carga durante o transporte, listando todos os CT-e incluídos na viagem. Clique em um MDF-e para ver seus detalhes, documentos vinculados e situação fiscal.",
    tags: ["operacao", "operação", "manifesto", "documentos", "fiscais", "consulte", "emitidos"],
  },
  {
    topic: "hipertms-03-operacao",
    category: "operacao",
    title: "Operação › MDF-e (Manifesto de Documentos Fiscais) › Entenda os status de um MDF-e",
    content: "- **Autorizado** — emitido e validado pela SEFAZ\n- **Encerrado** — viagem concluída e MDF-e encerrado\n- **Cancelado** — cancelamento autorizado\n\n> O encerramento do MDF-e deve ser realizado ao término de cada viagem para manter a conformidade fiscal.",
    tags: ["operacao", "operação", "manifesto", "documentos", "fiscais", "entenda", "status"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros",
    content: "> A área de Cadastros reúne todas as empresas e pessoas com quem você opera: clientes, remetentes, destinatários, parceiros transportadores e fornecedores.",
    tags: ["cadastros"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Clientes › Cadastre um novo cliente",
    content: "Acesse **Cadastros → Clientes** e clique em **Novo Cliente**.\n\nClientes são os tomadores de serviço — quem contrata e paga pelo frete. Preencha:\n\n- **Razão social e nome fantasia**\n- **CNPJ ou CPF**\n- **Endereço completo** — necessário para emissão de documentos fiscais\n- **Contatos** — e-mail, telefone e nome do responsável\n- **Dados bancários** — para cobrança e faturamento (aba Bancário)\n- **Limite de crédito** — define o valor máximo de operações em aberto\n\nSalve o cadastro. O cliente estará disponível para seleção em cotações e embarques.",
    tags: ["cadastros", "clientes", "cadastre", "novo", "cliente"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Clientes › Edite os dados de um cliente",
    content: "Na lista de clientes, localize o registro desejado e clique no nome ou no ícone de edição. Você pode atualizar qualquer informação nos campos disponíveis.\n\nPara adicionar ou alterar contatos, acesse a aba **Contatos** dentro do cadastro.",
    tags: ["cadastros", "clientes", "edite", "dados", "cliente"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Remetentes e Destinatários › Cadastre remetentes e destinatários",
    content: "Acesse **Cadastros → Remetentes e Destinatários** para gerenciar os pontos de coleta e entrega das suas operações.\n\nRemetentes são os locais de onde a carga parte; destinatários são onde ela será entregue. Eles podem ser diferentes do cliente que paga pelo frete.\n\nO formulário de cadastro é idêntico ao de clientes. Informe os dados cadastrais e o endereço completo para que o sistema consiga calcular rotas e gerar os documentos fiscais corretamente.",
    tags: ["cadastros", "remetentes", "destinatários", "cadastre"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Terceiros (Transportadores parceiros) › Cadastre transportadores e agregados",
    content: "Acesse **Cadastros → Terceiros** para registrar as transportadoras e motoristas autônomos parceiros que você contrata para realizar fretes.\n\nInforme os dados cadastrais, documentação (RNTRC, ANTT) e dados bancários para pagamento. Transportadores cadastrados aqui estarão disponíveis para seleção nos pedidos de frete de terceiros.",
    tags: ["cadastros", "terceiros", "transportadores", "parceiros", "cadastre", "agregados"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Fornecedores › Cadastre seus fornecedores de insumos e serviços",
    content: "Acesse **Cadastros → Fornecedores** para registrar empresas e pessoas que fornecem produtos ou serviços para sua operação (combustível, peças, pneus, serviços de manutenção, etc.).\n\nFornecedores cadastrados ficam disponíveis para seleção em pedidos de compra e solicitações internas.",
    tags: ["cadastros", "fornecedores", "cadastre", "seus", "insumos", "serviços"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Importação em massa › Importe múltiplos cadastros de uma vez",
    content: "Acesse **Cadastros → Importar CSV** para cadastrar múltiplas empresas de uma só vez a partir de uma planilha.\n\nBaixe o modelo de importação disponível na tela, preencha com os dados das empresas e faça o upload do arquivo. O sistema validará os dados e apresentará um relatório com os registros importados com sucesso e eventuais erros.\n\n> Ideal para migrar dados de outro sistema ou cadastrar uma base grande de clientes de forma ágil.",
    tags: ["cadastros", "importação", "massa", "importe", "múltiplos"],
  },
  {
    topic: "hipertms-04-cadastros",
    category: "cadastros",
    title: "Cadastros › Dicas para manter o cadastro organizado",
    content: "- Sempre informe o **CNPJ/CPF** para evitar duplicidades — o sistema alerta quando o documento já existe.\n- Mantenha os **endereços completos** (com CEP) para garantir a correta geração de documentos fiscais e cálculo de rotas.\n- Use a aba **Contatos** para registrar múltiplos responsáveis por empresa, com e-mails e telefones diferentes.",
    tags: ["cadastros", "dicas", "para", "manter", "cadastro", "organizado"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota",
    content: "> A área de Frota centraliza o gerenciamento de toda a sua operação de veículos e motoristas: cadastros, abastecimentos, manutenções e diárias.",
    tags: ["frota"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Veículos › Cadastre um novo veículo",
    content: "Acesse **Frota → Veículos** e clique em **Novo Veículo**.\n\nPreencha as informações do veículo:\n\n- **Placa e tipo** — identificação e categoria (truck, carreta, van, etc.)\n- **Proprietário** — frota própria ou agregado\n- **Capacidade** — peso e cubagem máximos\n- **Dados do documento** — RENAVAM, ano, chassi e cor\n- **Vencimentos** — CRLV, tacógrafo, extintor e outros documentos\n\nApós salvar, o veículo estará disponível para seleção em viagens e registros de abastecimento.",
    tags: ["frota", "veículos", "cadastre", "novo", "veículo"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Veículos › Acompanhe a situação da frota",
    content: "Na lista de veículos você visualiza cada veículo com seu status atual:\n\n- **Disponível** — pronto para operar\n- **Em viagem** — alocado em uma viagem ativa\n- **Em manutenção** — indisponível por manutenção\n- **Inativo** — veículo fora de operação\n\nClique em um veículo para ver seu histórico de viagens, abastecimentos, manutenções e leitura do odômetro.",
    tags: ["frota", "veículos", "acompanhe", "situação"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Veículos › Controle documentos e vencimentos",
    content: "Dentro do cadastro de cada veículo, acesse a aba **Documentos** para fazer upload de CRLV, laudos e outros arquivos. O sistema alerta sobre documentos próximos do vencimento para que você tome as providências com antecedência.",
    tags: ["frota", "veículos", "controle", "documentos", "vencimentos"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Motoristas › Cadastre um novo motorista",
    content: "Acesse **Frota → Motoristas** e clique em **Novo Motorista**.\n\nPreencha:\n\n- **Nome completo e CPF**\n- **CNH** — número, categoria e validade\n- **Contato** — telefone e e-mail\n- **Status** — disponível, em viagem, de folga ou inativo\n\nApós salvar, o motorista estará disponível para alocação em viagens.",
    tags: ["frota", "motoristas", "cadastre", "novo", "motorista"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Motoristas › Gerencie documentos do motorista",
    content: "Dentro do cadastro do motorista, acesse a aba **Documentos** para fazer upload da CNH, certidões e outros documentos necessários. Mantenha os vencimentos sempre atualizados.",
    tags: ["frota", "motoristas", "gerencie", "documentos", "motorista"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Abastecimentos › Registre um abastecimento",
    content: "Acesse **Frota → Abastecimentos** e clique em **Novo Registro**.\n\nInforme:\n\n- **Veículo** e **data** do abastecimento\n- **Leitura do odômetro** no momento do abastecimento\n- **Combustível** — tipo (diesel, gasolina, arla, etc.)\n- **Litros abastecidos** e **valor por litro**\n- **Posto** — local de abastecimento (opcional)\n\nO sistema calcula automaticamente o custo total e o consumo médio do veículo com base no histórico de abastecimentos.",
    tags: ["frota", "abastecimentos", "registre", "abastecimento"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Abastecimentos › Consulte o preço médio de referência",
    content: "Acesse **Frota → Preço de Referência** para configurar e consultar o preço médio de combustível utilizado como base nos cálculos de custo de viagem.\n\nMantenha este valor atualizado periodicamente para garantir cálculos de margem precisos.",
    tags: ["frota", "abastecimentos", "consulte", "preço", "médio", "referência"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Manutenções › Registre uma ordem de manutenção",
    content: "Acesse **Frota → Manutenções** e clique em **Nova Manutenção**.\n\nPreencha:\n\n- **Veículo** e **tipo de manutenção** (preventiva ou corretiva)\n- **Data de entrada e data prevista de saída**\n- **Descrição do serviço** — o que será feito\n- **Fornecedor/oficina** responsável pelo serviço\n- **Custo estimado**\n\nAo finalizar a manutenção, registre a data de saída e o custo final. O veículo voltará ao status **Disponível** automaticamente.",
    tags: ["frota", "manutenções", "registre", "ordem", "manutenção"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Manutenções › Programe revisões preventivas",
    content: "Dentro do cadastro de cada veículo, acesse a aba **Revisões** para programar manutenções preventivas por quilometragem ou por intervalo de tempo. O sistema alertará quando o vencimento se aproximar.",
    tags: ["frota", "manutenções", "programe", "revisões", "preventivas"],
  },
  {
    topic: "hipertms-05-frota",
    category: "frota",
    title: "Frota › Diárias de Motorista › Registre uma diária ou adiantamento",
    content: "Acesse **Frota → Diárias** para registrar os adiantamentos e diárias pagas aos motoristas durante as viagens.\n\nInforme o motorista, a viagem relacionada, o valor e a forma de pagamento. O registro fica vinculado ao financeiro da viagem para controle de margem.",
    tags: ["frota", "diárias", "motorista", "registre", "diária", "adiantamento"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro",
    content: "> A área Financeira reúne o controle de contas a pagar e a receber, faturamento, gestão de categorias, orçamento e contas bancárias.",
    tags: ["financeiro"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Contas a Pagar › Registre uma nova conta a pagar",
    content: "Acesse **Financeiro → Contas a Pagar** e clique em **Nova Conta**.\n\nPreencha:\n\n- **Fornecedor ou credor** — a quem o valor será pago\n- **Descrição** — identificação clara da despesa\n- **Categoria** — classificação contábil da despesa\n- **Valor e vencimento** — valor total e data de pagamento\n- **Parcelas** — caso o pagamento seja parcelado, informe a quantidade de parcelas\n- **Conta bancária** — de qual conta o pagamento sairá\n\nSalve para que a conta entre no fluxo de aprovação e pagamento.",
    tags: ["financeiro", "contas", "pagar", "registre", "nova", "conta"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Contas a Pagar › Registre o pagamento de uma conta",
    content: "Na lista de contas a pagar, localize a conta desejada e clique em **Pagar**. Confirme a data de pagamento, o valor e a conta bancária utilizada. O saldo da conta bancária é atualizado automaticamente.",
    tags: ["financeiro", "contas", "pagar", "registre", "pagamento", "conta"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Contas a Pagar › Acompanhe o status das contas",
    content: "- **Pendente** — ainda não vencida e não paga\n- **Vencida** — passou da data sem pagamento\n- **Paga** — liquidada\n- **Cancelada** — conta cancelada",
    tags: ["financeiro", "contas", "pagar", "acompanhe", "status"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Contas a Receber › Registre um novo recebível",
    content: "Acesse **Financeiro → Contas a Receber** e clique em **Nova Conta**.\n\nPreencha os dados do cliente, descrição, valor, vencimento e categoria. Recebíveis gerados a partir de embarques ou faturas são criados automaticamente pelo sistema.",
    tags: ["financeiro", "contas", "receber", "registre", "novo", "recebível"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Contas a Receber › Registre o recebimento",
    content: "Localize a conta na lista e clique em **Receber**. Confirme a data, o valor recebido e a conta bancária de destino. Caso o valor recebido seja diferente do original (desconto ou juros), informe a diferença.",
    tags: ["financeiro", "contas", "receber", "registre", "recebimento"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Faturas do Tomador (Faturamento de venda) › Crie uma fatura para o cliente",
    content: "Acesse **Financeiro → Faturas (tomador)** e clique em **Nova Fatura**.\n\nUma fatura reúne um conjunto de embarques do mesmo cliente para cobrança consolidada. O sistema permite selecionar os embarques já realizados e gerar a fatura com os valores correspondentes.\n\nApós emitida, a fatura segue um fluxo de aprovação e pode ser enviada ao cliente por e-mail.",
    tags: ["financeiro", "faturas", "tomador", "faturamento", "venda", "crie", "fatura", "para"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Faturas do Tomador (Faturamento de venda) › Acompanhe o status de uma fatura",
    content: "- **Rascunho** — em elaboração\n- **Enviada** — fatura enviada ao cliente\n- **Paga parcialmente** — parte do valor recebida\n- **Paga** — fatura liquidada\n- **Cancelada**",
    tags: ["financeiro", "faturas", "tomador", "faturamento", "venda", "acompanhe", "status", "fatura"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Faturas do Prestador (Faturas de terceiros) › Registre uma fatura de transportador parceiro",
    content: "Acesse **Financeiro → Faturas (prestador)** para registrar as cobranças recebidas de transportadores e prestadores de serviço.\n\nEssas faturas são geradas a partir das **ordens de serviço** de transporte realizadas por terceiros. Revise os valores, vincule à conta a pagar correspondente e registre o pagamento quando realizado.",
    tags: ["financeiro", "faturas", "prestador", "terceiros", "registre", "fatura", "transportador", "parceiro"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Categorias Financeiras › Organize seu plano de contas",
    content: "Acesse **Financeiro → Categorias** para criar e gerenciar as categorias de receitas e despesas.\n\nAs categorias permitem classificar cada conta a pagar e receber, facilitando relatórios e análise financeira por tipo de custo ou receita.\n\nOrganize as categorias em grupos para facilitar a visualização nos relatórios de orçamento.",
    tags: ["financeiro", "categorias", "financeiras", "organize", "plano", "contas"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Orçamento › Defina o orçamento anual",
    content: "Acesse **Financeiro → Orçamento** para estabelecer as metas de receita e os limites de despesa por categoria ao longo do ano.\n\nCom o orçamento configurado, o sistema compara os valores realizados com os planejados, permitindo acompanhar desvios e tomar decisões com mais clareza.",
    tags: ["financeiro", "orçamento", "defina", "anual"],
  },
  {
    topic: "hipertms-06-financeiro",
    category: "financeiro",
    title: "Financeiro › Contas Bancárias › Cadastre as contas bancárias da empresa",
    content: "Acesse **Financeiro → Contas Bancárias** para registrar as contas correntes e de poupança da empresa.\n\n> Esta seção é restrita a administradores.\n\nInforme banco, agência, número da conta e saldo inicial. As movimentações financeiras registradas no sistema atualizarão o saldo automaticamente, permitindo um controle de caixa atualizado.",
    tags: ["financeiro", "contas", "bancárias", "cadastre", "empresa"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação",
    content: "> A área de Precificação é onde você configura as regras que determinam quanto cobrar por cada frete. Aqui ficam suas tabelas de frete, serviços adicionais, margens e configurações fiscais.",
    tags: ["precificacao", "precificação"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Tabelas de Frete › Entenda os tipos de tabela",
    content: "O HiperTMS suporta dois modelos de precificação:\n\n- **FCL (Full Container Load / Carga Fechada)** — preço fixo por tipo de veículo e rota, independente do peso.\n- **LCL (Less Container Load / Carga Fracionada)** — preço calculado por peso, cubagem ou por unidade de volume.",
    tags: ["precificacao", "precificação", "tabelas", "frete", "entenda", "tipos", "tabela"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Tabelas de Frete › Acesse e gerencie suas tabelas",
    content: "Acesse **Precificação → Tabelas de Frete** para visualizar todas as tabelas cadastradas.\n\nA tela apresenta cada tabela com seu nome, tipo (FCL ou LCL), rotas de abrangência e situação (ativa ou inativa).",
    tags: ["precificacao", "precificação", "tabelas", "frete", "acesse", "gerencie", "suas"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Tabelas de Frete › Configure uma tabela FCL",
    content: "Dentro de uma tabela FCL, você define:\n\n- **Veículos** — quais tipos de veículo essa tabela cobre\n- **Origens e destinos** — rotas ou regiões de abrangência\n- **Valores por veículo** — preço de frete para cada combinação de rota e veículo\n\nVocê pode criar múltiplas tabelas para cobrir diferentes regiões ou perfis de cliente.",
    tags: ["precificacao", "precificação", "tabelas", "frete", "configure", "tabela"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Tabelas de Frete › Configure uma tabela LCL",
    content: "Dentro de uma tabela LCL, você define:\n\n- **Faixas de peso ou cubagem** — intervalos e os valores correspondentes\n- **Origens e destinos** — abrangência da tabela\n- **Mínimo de frete** — valor mínimo cobrado por embarque",
    tags: ["precificacao", "precificação", "tabelas", "frete", "configure", "tabela"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Tabelas de Frete › Vincule uma tabela a um contrato",
    content: "Para aplicar uma tabela específica a um cliente com acordo comercial, acesse **Precificação → Contratos** e associe a tabela desejada ao contrato do cliente. Isso garante que as cotações para esse cliente usem sempre a tabela negociada.",
    tags: ["precificacao", "precificação", "tabelas", "frete", "vincule", "tabela", "contrato"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Serviços Adicionais › Cadastre serviços cobrados além do frete",
    content: "Acesse **Precificação → Serviços Adicionais** para configurar cobranças complementares ao frete principal.\n\nExemplos: coleta expressa, entrega agendada, armazenagem, seguro adicional, pedágio, etc.\n\nPara cada serviço, defina:\n\n- **Nome e descrição** do serviço\n- **Forma de cálculo** — valor fixo, percentual sobre o frete ou por unidade (por kg, por volume, etc.)\n- **Valor ou percentual**\n\nOs serviços ativos ficam disponíveis para seleção no momento da cotação.",
    tags: ["precificacao", "precificação", "serviços", "adicionais", "cadastre", "cobrados", "além", "frete"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Margens › Configure os divisores de margem",
    content: "Acesse **Precificação → Margens** para definir os percentuais de markup aplicados sobre os custos de frete.\n\nAs margens funcionam como multiplicadores que transformam o custo operacional no preço final cobrado ao cliente. Você pode configurar margens diferentes para FCL, LCL e serviços adicionais.\n\n> Ajuste as margens com cuidado — elas impactam diretamente o preço calculado em todas as cotações.",
    tags: ["precificacao", "precificação", "margens", "configure", "divisores", "margem"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Regimes Tributários › Configure os regimes fiscais aplicados ao frete",
    content: "Acesse **Precificação → Regimes Tributários** para configurar as alíquotas e regras fiscais que incidem sobre seus fretes.\n\n> Esta seção é restrita a administradores da empresa.\n\nOs regimes tributários definem os impostos (ISS, PIS, COFINS, IR, CSLL) que compõem o custo fiscal de cada operação. Mantenha as alíquotas sempre atualizadas conforme a legislação vigente.",
    tags: ["precificacao", "precificação", "regimes", "tributários", "configure", "fiscais", "aplicados", "frete"],
  },
  {
    topic: "hipertms-07-precificacao",
    category: "precificacao",
    title: "Precificação › Contratos Comerciais › Crie um contrato com tabela acordada",
    content: "Acesse **Precificação → Contratos** e clique em **Novo Contrato**.\n\nUm contrato define as condições comerciais de um cliente específico: qual tabela de frete aplica, quais serviços estão incluídos, descontos especiais e prazo de validade.\n\nApós criado, o contrato é vinculado ao cadastro do cliente. Nas cotações para esse cliente, o sistema utilizará automaticamente as condições contratuais.",
    tags: ["precificacao", "precificação", "contratos", "comerciais", "crie", "contrato", "tabela", "acordada"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes",
    content: "> A área de Equipes organiza a colaboração interna: registro de atividades, gestão de tarefas, times e central de notificações.",
    tags: ["equipes"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes › Atividades › Acompanhe a linha do tempo da sua operação",
    content: "Acesse **Equipes → Atividades** para visualizar o histórico de ações realizadas no sistema — cotações criadas, embarques atualizados, viagens iniciadas, pagamentos registrados e muito mais.\n\nAs atividades são registradas automaticamente pelo sistema e permitem saber exatamente quem fez o quê e quando. Use os filtros de data, usuário e tipo de evento para encontrar uma ação específica.",
    tags: ["equipes", "atividades", "acompanhe", "linha", "tempo", "operação"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes › Tarefas › Crie e gerencie tarefas para sua equipe",
    content: "Acesse **Equipes → Tarefas** para criar, atribuir e acompanhar tarefas internas.\n\nPara criar uma tarefa, clique em **Nova Tarefa** e preencha:\n\n- **Título** — o que precisa ser feito\n- **Responsável** — membro da equipe que irá executar\n- **Data de vencimento** — prazo para conclusão\n- **Descrição** — detalhes e instruções adicionais\n- **Prioridade** — urgência da tarefa",
    tags: ["equipes", "tarefas", "crie", "gerencie", "para", "equipe"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes › Tarefas › Acompanhe o andamento das tarefas",
    content: "Na lista de tarefas, você visualiza todas as tarefas com seu status:\n\n- **Pendente** — aguardando início\n- **Em andamento** — sendo executada\n- **Concluída** — finalizada\n- **Atrasada** — passou do prazo sem conclusão\n\nClique em uma tarefa para ver detalhes, adicionar comentários e marcar como concluída.",
    tags: ["equipes", "tarefas", "acompanhe", "andamento"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes › Times › Organize sua equipe em times",
    content: "Acesse **Equipes → Equipes** para criar grupos de trabalho por área ou função (ex: Comercial, Operação, Financeiro).\n\nPara criar um time, clique em **Novo Time** e adicione os membros. Os times facilitam a atribuição de tarefas e o controle de acesso por área.",
    tags: ["equipes", "times", "organize", "equipe"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes › Times › Veja os detalhes de um time",
    content: "Clique em um time para ver seus membros, tarefas associadas e histórico de atividades do grupo.",
    tags: ["equipes", "times", "veja", "detalhes", "time"],
  },
  {
    topic: "hipertms-08-equipes",
    category: "equipes",
    title: "Equipes › Notificações › Fique por dentro do que acontece",
    content: "Acesse **Equipes → Notificações** para visualizar todos os avisos e alertas do sistema direcionados a você.\n\nAs notificações informam sobre eventos importantes como: vencimento de documentos, tarefas atribuídas, aprovações pendentes e atualizações em registros que você acompanha.\n\nClique em uma notificação para ser direcionado diretamente ao item relacionado.",
    tags: ["equipes", "notificações", "fique", "dentro", "acontece"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras",
    content: "> A área de Compras organiza o processo de aquisição de insumos e serviços: desde a solicitação interna até o recebimento do pedido e controle de estoque.",
    tags: ["compras"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Solicitações de Compra › Abra uma solicitação interna",
    content: "Acesse **Compras → Solicitações** e clique em **Nova Solicitação**.\n\nUma solicitação de compra é o pedido interno feito por um colaborador para adquirir um produto ou serviço. Preencha:\n\n- **Item solicitado** — descrição do produto ou serviço\n- **Quantidade** e **unidade** de medida\n- **Justificativa** — motivo da compra\n- **Data necessária** — quando o item é necessário\n- **Fornecedor sugerido** (opcional)\n\nApós enviar, a solicitação entra em fila de aprovação.",
    tags: ["compras", "solicitações", "compra", "abra", "solicitação", "interna"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Solicitações de Compra › Acompanhe o status de uma solicitação",
    content: "- **Pendente** — aguardando aprovação\n- **Aprovada** — autorizada e pronta para virar pedido\n- **Recusada** — não autorizada (com justificativa)\n- **Convertida em Pedido** — gerou um pedido de compra",
    tags: ["compras", "solicitações", "compra", "acompanhe", "status", "solicitação"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Solicitações de Compra › Aprove ou recuse uma solicitação",
    content: "Usuários com permissão de aprovação visualizam as solicitações pendentes na lista. Clique na solicitação, revise os dados e selecione **Aprovar** ou **Recusar**. No caso de recusa, informe o motivo.",
    tags: ["compras", "solicitações", "compra", "aprove", "recuse", "solicitação"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Pedidos de Compra › Crie um pedido de compra",
    content: "Acesse **Compras → Pedidos** e clique em **Novo Pedido**, ou converta uma solicitação aprovada em pedido diretamente pela tela de solicitações.\n\nNo pedido, informe:\n\n- **Fornecedor** — quem irá fornecer o item\n- **Itens e quantidades** — o que será comprado\n- **Valores unitários** — preço acordado com o fornecedor\n- **Condições de pagamento** — prazo e forma de pagamento\n- **Data de entrega prevista**\n\nAo confirmar, o pedido fica registrado e pode ser acompanhado até o recebimento.",
    tags: ["compras", "pedidos", "compra", "crie", "pedido"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Pedidos de Compra › Registre o recebimento de um pedido",
    content: "Quando os itens chegam, abra o pedido correspondente e clique em **Registrar Recebimento**. Informe a quantidade efetivamente recebida e a data. O estoque será atualizado automaticamente.",
    tags: ["compras", "pedidos", "compra", "registre", "recebimento", "pedido"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Estoque › Consulte o estoque disponível",
    content: "Acesse **Compras → Estoque** para visualizar todos os itens cadastrados com suas quantidades atuais.\n\nUse os filtros de categoria e nome para localizar um item específico. A tela exibe o estoque mínimo configurado e emite alertas quando o nível está abaixo do mínimo.",
    tags: ["compras", "estoque", "consulte", "disponível"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Estoque › Cadastre um novo produto no estoque",
    content: "Clique em **Novo Produto** e preencha:\n\n- **Nome e descrição** do item\n- **Unidade de medida** (un, kg, litro, etc.)\n- **Estoque mínimo** — quantidade mínima desejada para gatilho de alerta\n- **Estoque inicial** — quantidade disponível no momento do cadastro",
    tags: ["compras", "estoque", "cadastre", "novo", "produto"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Estoque › Registre uma movimentação de estoque",
    content: "Dentro de um produto, clique em **Nova Movimentação** para registrar uma entrada ou saída manual de estoque. Informe o tipo (entrada ou saída), a quantidade e o motivo.\n\nMovimentações geradas automaticamente por recebimento de pedidos também aparecem no histórico.",
    tags: ["compras", "estoque", "registre", "movimentação"],
  },
  {
    topic: "hipertms-09-compras",
    category: "compras",
    title: "Compras › Fornecedores (Compras) › Consulte e cadastre fornecedores homologados",
    content: "Acesse **Compras → Fornecedores** para visualizar os fornecedores disponíveis para uso nos pedidos de compra.\n\nPara adicionar um fornecedor, acesse **Cadastros → Fornecedores** e registre o novo parceiro. Ele estará disponível automaticamente na área de Compras.",
    tags: ["compras", "fornecedores", "consulte", "cadastre", "homologados"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração",
    content: "> A área de Administração concentra as configurações da sua empresa no sistema: usuários, perfil, automações e assinatura. O acesso a esta área é restrito a administradores.",
    tags: ["administracao", "administração"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Painel Administrativo › Acesse o painel de configurações",
    content: "Acesse **Administração** no menu lateral para ver o painel com resumo das configurações ativas, usuários cadastrados e situação da assinatura.",
    tags: ["administracao", "administração", "painel", "administrativo", "acesse", "configurações"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Perfil da Empresa › Atualize os dados da sua empresa",
    content: "Acesse **Administração → Perfil da Empresa** para editar as informações cadastrais do seu negócio:\n\n- **Razão social e nome fantasia**\n- **CNPJ e inscrição estadual**\n- **Endereço da sede**\n- **Logotipo** — imagem exibida nos documentos e no sistema\n- **Dados de contato** — telefone e e-mail institucional\n\nMantenha estas informações sempre atualizadas, pois elas são utilizadas na emissão de documentos fiscais e no cabeçalho dos relatórios.",
    tags: ["administracao", "administração", "perfil", "empresa", "atualize", "dados"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Usuários › Adicione um novo usuário",
    content: "Acesse **Administração → Usuários** e clique em **Novo Usuário**.\n\nPreencha o nome, e-mail e defina o perfil de acesso. O usuário receberá um e-mail de convite para criar sua senha e acessar o sistema.",
    tags: ["administracao", "administração", "usuários", "adicione", "novo", "usuário"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Usuários › Gerencie as permissões de um usuário",
    content: "Dentro do cadastro de cada usuário, acesse a aba **Permissões** para definir quais módulos e ações este usuário pode acessar.\n\nAs permissões seguem um modelo granular — você pode permitir, por exemplo, que o usuário visualize cotações mas não possa editá-las, ou que acesse o financeiro sem ver os valores de custo.",
    tags: ["administracao", "administração", "usuários", "gerencie", "permissões", "usuário"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Usuários › Desative um usuário",
    content: "Quando um colaborador sair da empresa ou precisar ter o acesso suspenso, localize o usuário na lista e clique em **Desativar**. O usuário perde o acesso imediatamente, mas seu histórico de atividades é preservado.",
    tags: ["administracao", "administração", "usuários", "desative", "usuário"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Perfis de Acesso (Roles) › Consulte os perfis disponíveis",
    content: "Acesse **Administração → Perfis** para visualizar os perfis de acesso pré-definidos no sistema e entender quais permissões cada perfil concede.\n\nVocê pode consultar esta referência ao configurar um novo usuário e decidir qual perfil se encaixa melhor na função do colaborador.",
    tags: ["administracao", "administração", "perfis", "acesso", "roles", "consulte", "disponíveis"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Numerações (Sequências) › Configure as sequências numéricas dos documentos",
    content: "Acesse **Administração → Numerações** para definir o formato e o número inicial das sequências automáticas do sistema — cotações, embarques, faturas e outros documentos.\n\n> Esta configuração é aplicada uma única vez durante a implantação. Alterações posteriores devem ser feitas com cuidado para evitar numerações duplicadas.",
    tags: ["administracao", "administração", "numerações", "sequências", "configure", "numéricas", "documentos"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Parâmetros de Automação › Configure regras automáticas da operação",
    content: "Acesse **Administração → Automação** para configurar parâmetros que o sistema aplica automaticamente em determinadas situações.\n\nExemplos de automações disponíveis: cálculo automático de fretes ao cadastrar embarques, alertas de margem mínima em cotações, e geração automática de tarefas em eventos operacionais.",
    tags: ["administracao", "administração", "parâmetros", "automação", "configure", "regras", "automáticas", "operação"],
  },
  {
    topic: "hipertms-10-administracao",
    category: "administracao",
    title: "Administração › Assinatura e Plano › Veja e gerencie sua assinatura",
    content: "Acesse **Administração → Assinatura** para consultar o plano atual, o histórico de faturas e as opções de upgrade.\n\nNesta tela você também pode atualizar os dados de pagamento e verificar o ciclo de cobrança vigente.\n\n*Voltar ao início: [Índice](./hipertms-indice.md)*",
    tags: ["administracao", "administração", "assinatura", "plano", "veja", "gerencie"],
  },
];
